### ISSUE TITLE
S7 map a little to small

### ISSUE THREAD

**Issue by Agent-Theta** [Dinip/hermitcraft#11]
possibly expand the S7 map a bit due to some locations being off map (X's witch farm, maybe a few i don't know). problem will probably get worse as season goes on (maybe). would probably wait until there are a few more off map.

Just a suggestion :)

**Comment by Dinip** [comment]
yeah, I should expand it a bit more... @Huntracony mentioned in pull #8 because Etho's ice fortress was out of the map. I will expand it and update the online map during this weekend.
Thanks for letting me know, not paying much attention to S7 videos right now 😕

**Comment by Dinip** [comment]
Season 7 map was expanded from 6000x6000 (-3000, 3000) to 8000x8000 (-4000, 4000).
Might be a bit buggy because of the "hard" cache used to serve the map.
