### ISSUE TITLE
Miss-alignment on the Overworld - 2d Topdown - Empty map

### ISSUE THREAD

**Issue by moltenwolfcub** [Dinip/hermitcraft#116]
On the Overworld 2d topdown empty map the whole map is mis-aligned the coordinates for bases and other locations are right but the actual background render is wrong

Photos show the empty 2d and filled 2d where you can see the misaligned map image

Empty map mis-aligned
![mis-aligned map](https://user-images.githubusercontent.com/90516933/147497183-d6761772-92e9-420f-b87c-a944208e52f5.png)

Filled map with correct alignment
![mis-aligned map right](https://user-images.githubusercontent.com/90516933/147497185-78adc1b0-3ab0-4626-ba17-24389b67736d.png)

**Comment by Dinip** [comment]
ohh... definitively something is wrong, I'll check what's happening.
Thanks for the finding!

**Comment by Dinip** [comment]
Fixed! Thanks 😀
