### ISSUE TITLE
Season 9 map is showing only starter bases

### ISSUE THREAD

**Issue by juanpsm** [Dinip/hermitcraft#125]
The map for [season9](https://hermitcraftmaps.confusion.pt/season9/) shows only starter bases although file [season9/markers.js](https://github.com/Dinip/hermitcraft/blob/master/season9/markers.js) has more data (planned bases, shops, mimnigames, etc)

![image](https://user-images.githubusercontent.com/11953173/167506993-db185356-b008-4ad6-9cef-e70b1fd0d218.png)

**Comment by juanpsm** [comment]
all other data is commented out for some reason

**Comment by Dinip** [comment]
There is a PR pending approval. I saw the email but I forgot the check it :/
