### ISSUE TITLE
New hermit icons and skin upgrades

### ISSUE THREAD

**Issue by lochlainnible** [Dinip/hermitcraft#139]
![bdubs2](https://github.com/Dinip/hermitcraft/assets/65836345/aedd8f60-b7a6-46d9-81a8-ed0ee6b887e0) bdubs2.png
![cub2](https://github.com/Dinip/hermitcraft/assets/65836345/f084422c-3310-4847-8c39-665c5f233245) cub2.png
![joel](https://github.com/Dinip/hermitcraft/assets/65836345/4b140d61-20fa-4540-ab50-3208ed5952a6) joel.png
![skizz](https://github.com/Dinip/hermitcraft/assets/65836345/9262d871-86cd-4756-8ab4-2187ce84729c) skizz.png

These are 4 new icons to possibly add to the current list.

**Comment by Dinip** [comment]
The idea is to update Bdubs and Cub and add the Joel and Skizz, right?

**Comment by Dinip** [comment]
Yeah, that's why I asked what was the idea.
Just updated to keep the "old" ones to be used on the previous seasons and added the new ones as `bdubs2.png` and `cub2.png`.

**Comment by lochlainnible** [comment]
awesome, thank you so much!

**Comment by Dinip** [comment]
Also updated the markers file to reflect the changes on season 10
